### ISSUE TITLE
rasterStack / terra interface

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/rosettaPTF#3]
Given a `rasterStack` of required inputs, wrap `raster::calc()` (or `terra` equivalent) such that arbitrarily large input can be iterated over, resulting in a new `rasterStack` of ROSETTA output.

**Comment by brownag** [comment]
Reopened b/c https://github.com/ncss-tech/rosettaPTF/commit/1a2f56566c80fcbd5f1fad2bc44ab6dc0d3dd278 addresses the function definition for the RasterStack method but will not work with arbitrarily large input yet. The implementation can be refactored to be more generic. 

Also will address a terra equivalent.

**Comment by brownag** [comment]
closed in #4
