### ISSUE TITLE
`"rosetta.rosetta.SoilData"` class is not preserved with reticulate >=1.29

### ISSUE THREAD

**Issue by brownag** [ncss-tech/rosettaPTF#8]
The following line of code worked with prior versions of {reticulate}

https://github.com/ncss-tech/rosettaPTF/blob/0aa61b959bdf6c5681148edb58ceb055ac43e48b/R/run_rosetta.R#L30

With reticulate >=1.29 the following error occurs:

```
Error in `py_call_impl(callable, call_args$unnamed, call_args$named)`: 
rosetta.rosetta.RosettaError: soildata must be a SoilData instance
```

This is because recent changes in python -> R object conversion result in a `"list"` object rather than a proper subclass of `"python.builtin.list"`. 

On reticulate 1.28 or earlier `rosetta_module$SoilData$from_array(x)` returns an object of class `c("rosetta.rosetta.SoilData", "python.builtin.list", "typing.Generic", "python.builtin.object")`

At this point I am not certain there is a mechanism to prevent this automatic conversion from happening. While conversion to basic R types is handy for direct use of python results in R, it drops all of the class information which may be required for either dispatch on R side or (in this case) within specific Python functions.

**Comment by dylanbeaudette** [comment]
Yikes, thanks for reporting. Do we need to ask Todd to make any changes in the python module to make access via reticulate simpler?

**Comment by brownag** [comment]
I was not implying we should work around this by making changes to the rosetta-soil module, but I suppose that is an option. If it allowed for a list of SoilDatum rather than a SoilData object then it would work.

The issue is much deeper than that though. I think it is a case that was not considered in recent changes to reticulate. I have found other unexpected changes in behavior with 1.29 and have been wanting to develop reproducible examples and have {reticulate} fix them or provide an alternative.

**Comment by dylanbeaudette** [comment]
OK, you are the expert on this topic. Let me know if/when we need to involve Todd. He has always been great about making changes based on our feedback.

**Comment by brownag** [comment]
Note that the following call to `r_to_py()` converts the R list result of `$from_array()` to `"python.builtin.list"` ... but setting "class" attribute to include `"rosetta.rosetta.SoilData"` does not fix the issue. The result object is still not recognized as/converted to an instance of SoilData because after the initial conversion to R list that information is lost.

```r
SoilDataFromArray <- function(x) {
  res <- r_to_py(rosetta_module$SoilData$from_array(x))
  class(res) <- c("rosetta.rosetta.SoilData", "python.builtin.list", "typing.Generic", "python.builtin.object")
  res
}
```

**Comment by brownag** [comment]
The issue is roundtripping objects from Python->R->Python, and also making sure R knows the provenance of objects when they reflect a custom Python type. IMO not really a problem with the Python code itself.

My gut feeling--and I am _not_ an expert in the latest and greatest python idioms--is that there is nothing "wrong" with defining a custom subclass of "python.builtin.list" (or "python.builtin.dict")... so Todd shouldn't have to rework class definitions  just because in some common cases (e.g. object types defined by tensorflow) it works to convert a list subclass directly to the R "list" type 

We currently do not dispatch any R methods on "rosetta.rosetta.SoilData", but in theory we _could_, and that would be additional reason to retain the class information beyond the fact that the Python code requires a class of that type. I think one could argue the SoilData class as a container of SoilDatum is somewhat superfluous because it doesn't offer much more than "python.builtin.list" beyond the name... but that doesn't mean that information about it should be dropped by default.

**Comment by brownag** [comment]
This has been resolved. I defined a custom `py_to_r()` S3 wrapper method for the `rosetta.rosetta.SoilData` objects that does no conversion such that the full set of python classes is retained.

https://github.com/ncss-tech/rosettaPTF/blob/7fe72b68c906bc98ed250f95b2a21b13dc1b274a/R/rosetta_utils.R#L14-L21
